### ISSUE TITLE
Buffer tests will universally fail if test cases are less than a specified length

### ISSUE THREAD

**Issue by sushisharkjl** [Achierius/aolc#12]
[As defined,](https://github.com/Achierius/aolc/blob/6658f7954611de969b1fe1de017ad96bbfadf759/tests/compare_buffer_functions.cpp#L168) the `compare_buffer_functions` logic will fail if there is any difference between the two provided buffers up to a length of `kMaxBufferSize`, as opposed to the expected behaviour where we only care about differences up to a length of `n`. 

See #11.

**Comment by Achierius** [comment]
The thought here is that the buffers are zeroed to begin with, so they'll only differ past the end of the 'actual' buffer-len if the functions write beyond their bounds; since according to the C standard writes beyond the end of the provided buffer are undefined behavior, check the entire buffer makes sure that the user memfn isn't doing anything funky (same idea with the buffer canaries that sit between the buffers).
